#!/bin/bash

if [ -d "./.env" ]; then
  echo "Remove ./env directory and try again"
  exit 1;
fi

python3 -m venv .env
source .env/bin/activate
pip install transformers
pip install 'transformers[torch]'
pip install 'transformers[tf-cpu]'
pip install 'transformers[flax]'

exit 0;
